DROOLS-1460 DMN extension for kie-server (#836)
* Adding DMN to ee7, but still not enough.

* Add dependency in order to be fetched from assembly file.

* Fix typo preventing to locate the correct provider.

* Hello world.

* .

* HelloWorld with DMN Models (using JSON marshalling)

* Tests not working.

* Despite, test still failing.

* still issues.

java.lang.RuntimeException: Unknown resource type: ResourceType = 'Decision Model and Notation'
	at org.drools.compiler.builder.impl.KnowledgeBuilderImpl.addPackageForExternalType(KnowledgeBuilderImpl.java:809)
	at org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl.buildOthers(CompositeKnowledgeBuilderImpl.java:240)
	at org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl.build(CompositeKnowledgeBuilderImpl.java:107)
	at org.drools.compiler.kie.builder.impl.AbstractKieModule.buildKnowledgePackages(AbstractKieModule.java:244)
	at org.drools.compiler.kie.builder.impl.AbstractKieProject.verify(AbstractKieProject.java:64)
	at org.drools.compiler.kie.builder.impl.KieBuilderImpl.buildKieProject(KieBuilderImpl.java:236)
	at org.drools.compiler.kie.builder.impl.KieBuilderImpl.buildKieModule(KieBuilderImpl.java:228)
	at org.kie.scanner.KieRepositoryScannerImpl.build(KieRepositoryScannerImpl.java:221)
	at org.kie.scanner.KieRepositoryScannerImpl.buildArtifact(KieRepositoryScannerImpl.java:171)
	at org.kie.scanner.KieRepositoryScannerImpl.loadArtifact(KieRepositoryScannerImpl.java:127)
	at org.kie.scanner.KieRepositoryScannerImpl.loadArtifact(KieRepositoryScannerImpl.java:122)
	at org.drools.compiler.kie.builder.impl.KieRepositoryImpl.loadKieModuleFromMavenRepo(KieRepositoryImpl.java:197)
	at org.drools.compiler.kie.builder.impl.KieRepositoryImpl.getKieModule(KieRepositoryImpl.java:143)
	at org.drools.compiler.kie.builder.impl.KieRepositoryImpl.getKieModule(KieRepositoryImpl.java:120)
	at org.drools.compiler.kie.builder.impl.KieServicesImpl.newKieContainer(KieServicesImpl.java:184)
	at org.drools.compiler.kie.builder.impl.KieServicesImpl.newKieContainer(KieServicesImpl.java:172)
	at org.kie.server.integrationtests.dmn.DMNIntegrationTest.deployArtifacts(DMNIntegrationTest.java:52)

* Finally working - thanks Maciej

* Make Hello world in 1+1 style evaluating function definition DMN model.

* Use DMNEvaluationContext for payload of context and coordinates

* NOT WORKING because unable to serialize DMN AST nodes ootb

* wip still missing to align new DMN API, JMS and other functionalities.

* Align with DROOLS-1434 for moving public interfaces to kie-dmn-api module

* Avoid the need for kie-dmn-core if only to create a new DMNContext ..

.. and have the DMN Client interface generate the newContext() similarly
to what DMNRuntime do.

* .

* will require kie-dmn-api signature as `Object getSourceReference()`

* test working except JSON is Integer instead of BigDecimal on unmarshal client side

* REVERT ME: attempted to customize JSONMarshaller for primitive type.

* Revert "REVERT ME: attempted to customize JSONMarshaller for primitive type."

This reverts commit 49c784722510be15b5f8e4f6370e4c4374a4012f.

* DMN coercing number manually if the response is JSON.

* JMS support and misc clean-up.

* Add to kie-server-client OSGi feature as DMN client depends on kie-dmn-api

* .

* disable DMN extension during kie-server-integ-test-optaplanner ..

.. similarly to other extensions.

* REVERT ME: disabling temporarily DMN integ-test from the CI build

* Revert "REVERT ME: disabling temporarily DMN integ-test from the CI build"

This reverts commit 665cd76e090ceac4efd89a20161a058e69a58b0c.

* disable DMN extension during kie-server-integ-test-optaplanner (pt2)..

.. similarly to other extensions.

* Improve DMNKieServerExtension.isActive()

* Ensure kie-server-tests modules are executed one at a time

Ref commit 3a92c62 of PR droolsjbpm/droolsjbpm-integration#447 
This is an artificial dependency to make sure the kie-server-tests modules are executed one at a time during
parallel build (otherwise the tests fail because of conflicting port binding)